[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/template',
    'pallets/erc20',
    'pallets/deeper-node',
    'pallets/micropayment',
    'pallets/credit',
    'runtime',
]
